# =========================================================================
# DADOS ESTRUTURAIS
# =========================================================================

dictGR_ANP7990 = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916347", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916347", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "704 - Transferência da União Referente a Royalties do Petróleo e Gás Natural", 
    "FonteRJ": "104 - Transferência da União Ref. a Comp. Financ. pela Exploração de Recursos Naturais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (704.104)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "4879 - COTA-PARTE DA COMP. FINANC. DOS ROYALTIES PELA PRODUÇÃO DO PETRÓLEO - ATÉ 5% - PÓS-SAL", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1399990103 - Out Rec Pat - Royalties pela Produção do Petróleo - Até 5%"
}
dictGR_ANP9478 = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916347", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916347", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "704 - Transferência da União Referente a Royalties do Petróleo e Gás Natural", 
    "FonteRJ": "104 - Transferência da União Ref. a Comp. Financ. pela Exploração de Recursos Naturais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (704.104)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "4881 - ROYALTIES PELA PRODUÇÃO DO PETRÓLEO - EXCEDENTE A 5%", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1399990105 - Out Rec Pat - Royalties pela Produção do Petróleo - Excedente a 5%"
}
dictGR_PEA = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916347", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916347", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "704 - Transferência da União Referente a Royalties do Petróleo e Gás Natural", 
    "FonteRJ": "104 - Transferência da União Ref. a Comp. Financ. pela Exploração de Recursos Naturais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (704.104)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "5686 - COTA PARTE PART. ESPECIAL EXP. PETR. E GAS NATURAL LEI 9.478/97", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1399990106 - Out Rec Pat - Participação Especial Exploração do Petróleo"
}
dictGR_FEP = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916347", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916347", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "704 - Transferência da União Referente a Royalties do Petróleo e Gás Natural", 
    "FonteRJ": "104 - Transferência da União Ref. a Comp. Financ. pela Exploração de Recursos Naturais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (704.104)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "5723 - COTA PARTE FUNDO ESPECIAL DO PETROLEO", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1399990107 - Out Rec Pat - Fundo Especial do Petróleo - FEP"
}
dictGR_FPE = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916339", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916339", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "500 - Recursos não Vinculados de Impostos", 
    "FonteRJ": "107 - Recursos não Vinculados de Impostos - Transferência Constitucionais de Impostos", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (500.107)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "2038 - COTA-PARTE DO FUNDO DE PARTICIPAÇÃO DOS ESTADOS - FPE", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1711500101 - Cota-Parte FPE - Fundo de Participação dos Estados e do DF - Principal"
}
dictGR_IPI = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916363", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916363", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "500 - Recursos não Vinculados de Impostos", 
    "FonteRJ": "107 - Recursos não Vinculados de Impostos - Transferência Constitucionais de Impostos", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (500.107)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "2040 - COTA-PARTE DO ESTADO - IPI", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1711530101 - Cota-Parte IPI Exportação - Principal - LC 61/89"
}
dictGR_CFM = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916371", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916371", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "708 - Transferência da União Referente à Compensação Financeira de Recursos Minerais", 
    "FonteRJ": "101 - Transferência da União - Compensação Financeira de Recursos Minerais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (708.101)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "5682 - Cota-Parte da Compensação Financeira de Recursos Minerais", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1344020101 - Compensação Financeira pela Exploração de Recursos Minerais - Principal"
}
dictGR_CFH = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "291638X", 
    "DomicilioBancarioCompleto": "001 - 2234 - 291638X", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "709 - Transferência da União referente à Compensação Financeira de Recursos Hídricos", 
    "FonteRJ": "101 - Transferência da União - Compensação Financeira de Recursos Hídricos", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (709.101)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "5722 - COTA PARTE DA COMPENSAÇÃO FINANCEIRA RECURSOS HIDRICOS", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1345032101 - Utilização de Recursos Hídricos - Demais Empresas - Principal"
}
dictGR_CIDE = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916509", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916509", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "750 - Recursos da Contribuição de Intervenção no Domínio Econômico - CIDE", 
    "FonteRJ": "126 - Recursos da Contribuição de Intervenção no Domínio Econômico - CIDE", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (750.126)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "2044 - COTA-PARTE DO ESTADO NA CONTRIBUIÇÃO DE INTERVENÇÃO NO DOMÍNIO ECONÔMICO - CIDE", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1711540101 - Cota-Parte Contribuição de Intervenção no Domínio Econômico - CIDE - Principal"
}
dictGR_ADO = {
    "ExtraOrcamentario": False, 
    "TipoDocumento": "Orçamentário", 
    "UG": "999900", 
    "DomicilioBancario": "2916312", 
    "DomicilioBancarioCompleto": "001 - 2234 - 2916312", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "501 - Outros Recursos não Vinculados", 
    "FonteRJ": "101 - Outros Recursos não Vinculados - Ordinários Não Provenientes de Impostos-Tesouro", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (501.101)", 
    "Convenio": "000000 - Convênio não identificado", 
    "TipoPatrimonial": "Transferências Intergovernamentais Recebidas", 
    "ItemPatrimonial": "2055 - DEMAIS TRANSFERÊNCIAS DA UNIÃO", 
    "OperacaoPatrimonial": "2469 - Reconhecimento, Arrecadação e Recolhimento", 
    "NaturezaReceita": "1719990101 - Outras Transferências da União - Principal"
}

dictPD_PASEP_ROYALTIES = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "2916347", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916347", 
    "DomicilioBancarioDestino": "BCO AUTENT", 
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "704 - Transferência da União Referente a Royalties do Petróleo e Gás Natural", 
    "FonteRJ": "104 - Transferência da União Ref. a Comp. Financ. pela Exploração de Recursos Naturais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (704.104)", 
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_FPE = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "2916339", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916339", 
    "DomicilioBancarioDestino": "BCO AUTENT", 
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "500 - Recursos não Vinculados de Impostos", 
    "FonteRJ": "107 - Recursos não Vinculados de Impostos - Transferência Constitucionais de Impostos", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (500.107)", 
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_IPI = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "2916363", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916363",
    "DomicilioBancarioDestino": "BCO AUTENT",
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT",
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "500 - Recursos não Vinculados de Impostos", 
    "FonteRJ": "107 - Recursos não Vinculados de Impostos - Transferência Constitucionais de Impostos", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (500.107)",
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_CFM = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "2916371", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916371",
    "DomicilioBancarioDestino": "BCO AUTENT",
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "708 - Transferência da União Referente à Compensação Financeira de Recursos Minerais", 
    "FonteRJ": "101 - Transferência da União - Compensação Financeira de Recursos Minerais", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (708.101)",
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_CFH = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "291638X", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 291638X", 
    "DomicilioBancarioDestino": "BCO AUTENT",
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente",
    "Fonte": "709 - Transferência da União referente à Compensação Financeira de Recursos Hídricos", 
    "FonteRJ": "101 - Transferência da União - Compensação Financeira de Recursos Hídricos",
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento",
    "DetalhamentoFonte": "000000 - Sem detalhamento - (709.101)",
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_CIDE = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP", 
    "DomicilioBancarioOrigem": "2916509", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916509", 
    "DomicilioBancarioDestino": "BCO AUTENT",
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente", 
    "Fonte": "750 - Recursos da Contribuição de Intervença no Domínio Econômico - CIDE", 
    "FonteRJ": "126 - Recursos da Contribuição de Intervença no Domínio Econômico - CIDE", 
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (750.126)",
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}
dictPD_PASEP_ADO = {
    "UG": "999900", 
    "UGFavorecida": "370200", 
    "Regularizacao": "OB Regularização Financeira", 
    "JustificativaRegularizacao": "RETENÇÃO-PASEP",
    "DomicilioBancarioOrigem": "2916312", 
    "DomicilioBancarioOrigemCompleto": "001 - 2234 - 2916312", 
    "DomicilioBancarioDestino": "BCO AUTENT",
    "DomicilioBancarioDestinoCompleto": "001 - 2234 - BCO AUTENT", 
    "IEF": "1 - Recursos do Exercício Corrente",
    "Fonte": "501 - Outros Recursos não Vinculados", 
    "FonteRJ": "101 - Outros Recursos não Vinculados - Ordinários Não Provenientes de Impostos-Tesouro",
    "TipoDetalhamentoFonte": "0 - Sem Detalhamento", 
    "DetalhamentoFonte": "000000 - Sem detalhamento - (501.101)",
    "Convenio": "000000 - Convênio não identificado", 
    "Indice": "1,000", 
    "TipoPatrimonial": "Pagamentos a Regularizar", 
    "ItemPatrimonial": "5678 - Pagamentos (Por Ofício) a Regularizar - FONTES TESOURO", 
    "OperacaoPatrimonial": "4962 - Pagamentos (Por Ofícios) a Regularizar - FONTES TESOURO"
}

dict_map_gr = {
    1: dictGR_ANP7990, 2: dictGR_ANP9478, 3: dictGR_PEA,
    4: dictGR_FEP, 5: dictGR_FPE, 6: dictGR_IPI,
    7: dictGR_CFM, 8: dictGR_CFH, 9: dictGR_CIDE,
    10: dictGR_ADO
}
dict_map_pd = {
    11: dictPD_PASEP_ROYALTIES, 12: dictPD_PASEP_ROYALTIES,
    13: dictPD_PASEP_ROYALTIES, 14: dictPD_PASEP_ROYALTIES,
    15: dictPD_PASEP_FPE, 16: dictPD_PASEP_IPI,
    17: dictPD_PASEP_CFM, 18: dictPD_PASEP_CFH,
    19: dictPD_PASEP_CIDE, 20: dictPD_PASEP_ADO
} 